worker_processes auto;
pid logs/nginx.pid;

env RUST_BACKTRACE=full;

events {
    worker_connections 1024;
}
error_log logs/error.log info;

wasm {
    module rate_limit_filter          ../../target/wasm32-wasip1/wasm-release/rate_limit.wasm;
    module api_key_filter             ../../target/wasm32-wasip1/wasm-release/api_key.wasm;
    module header_manipulation_filter ../../target/wasm32-wasip1/wasm-release/header_manipulation.wasm;
    module logging_filter             ../../target/wasm32-wasip1/wasm-release/logging.wasm;
    module passthrough_filter         ../../target/wasm32-wasip1/wasm-release/passthrough.wasm;
}

http {
    default_type application/octet-stream;
    client_body_temp_path tmp/client_body;
    proxy_temp_path       tmp/proxy;
    fastcgi_temp_path     tmp/fastcgi;
    scgi_temp_path        tmp/scgi;
    uwsgi_temp_path       tmp/uwsgi;

    proxy_http_version 1.1;
    proxy_set_header   Connection "";

    log_format gw_json escape=json '{"time":"$time_iso8601","method":"$request_method","uri":"$request_uri","status":$status,"bytes":$body_bytes_sent}';
    access_log logs/access.log gw_json;

    upstream svc-v2 {
        server 127.0.0.1:8082 weight=1;
        keepalive 32;
    }

    upstream svc-v1 {
        server 127.0.0.1:8081 weight=1;
        keepalive 32;
    }

    server {
        listen 9000;

        location /api/v2/ {
            proxy_wasm api_key_filter '{"api_keys":["secret-key-1","secret-key-2","rl-test-key"]}';
            proxy_wasm rate_limit_filter '{"requests_per_second":10}';
            proxy_wasm header_manipulation_filter '{"request":{"add":{"X-Gateway":"nginx-wasm-gw"},"remove":["X-Internal-Secret"]},"response":{"add":{"X-Gateway":"nginx-wasm-gw","X-Response-Time":"measured"},"remove":["Server"]}}';
            proxy_wasm logging_filter;
            proxy_pass http://svc-v2;
        }

        location /api/v1/ {
            proxy_wasm api_key_filter '{"api_keys":["secret-key-1","secret-key-2","rl-test-key"]}';
            proxy_wasm rate_limit_filter '{"requests_per_second":10}';
            proxy_wasm header_manipulation_filter '{"request":{"add":{"X-Gateway":"nginx-wasm-gw"},"remove":["X-Internal-Secret"]},"response":{"add":{"X-Gateway":"nginx-wasm-gw","X-Response-Time":"measured"},"remove":["Server"]}}';
            proxy_wasm logging_filter;
            proxy_pass http://svc-v1;
        }
    }
}
