worker_processes auto;
error_log logs/error.log info;
pid logs/nginx.pid;

env RUST_BACKTRACE=full;

events {
    worker_connections 1024;
}

wasm {
    module passthrough_filter ../../target/wasm32-wasip1/wasm-release/passthrough.wasm;
}

http {
    default_type application/octet-stream;
    client_body_temp_path tmp/client_body;
    proxy_temp_path       tmp/proxy;

    server {
        listen 9000;

        location / {
            proxy_wasm passthrough_filter;
            return 200 "ok\n";
        }
    }
}
